name: Test

on:
  push:
    branches:
      - main
    paths:
      - "textstat_cli/**"
      - ".python-version"
      - "pyproject.toml"
      - "uv.lock"
      - "tests/**"
      - ".github/workflows/test.yml"
  pull_request:
    branches:
      - main
    paths:
      - "textstat_cli/**"
      - ".python-version"
      - "pyproject.toml"
      - "uv.lock"
      - "tests/**"
      - ".github/workflows/test.yml"

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4 # v10.1.0
        with:
          enable-cache: "auto"
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
        with:
          python-version-file: ".python-version"
      - name: Lint
        run: |
          uv run ruff check textstat_cli
  test:
    name: Test the library
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4 # v10.1.0
        with:
          enable-cache: "auto"
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
        with:
          python-version: ${{ matrix.python-version }}
      - name: Test
        run: |
          uv run -m unittest discover tests
          uv run textstat_cli samples/lorium.txt
