name: Test

env:
  name: textstat_cli
  command: textstat

on:
  push:
    branches:
      - main
    paths:
      - "textstat_cli/**"
      - ".python-version"
      - "pyproject.toml"
      - "uv.lock"
      - "tests/**"
      - ".github/workflows/test.yml"
  pull_request:
    branches:
      - main
    paths:
      - "textstat_cli/**"
      - ".python-version"
      - "pyproject.toml"
      - "uv.lock"
      - "tests/**"
      - ".github/workflows/test.yml"

jobs:
  lint:
    name: Run some linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Lint
        run: |
          uv run ruff textstat_cli
  test:
    name: Test the library
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt
      - name: Test
        run: |
          python3 -m unittest discover tests
          python3 -m ${{env.name}} --help
          python3 -m ${{env.name}} samples/lorium.txt
  test-installation:
    name: Test installing the library
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run setup.py
        run: python3 setup.py install
